### ISSUE TITLE
Mismatch in the count of koroks

### ISSUE THREAD

**Issue by alcabcucu** [lud99/totk-unexplored#3]
First of all, thanks for the amazing job.
I have noticed there is a problem with the count of koroks. I have found 562 in my game, but TotK Unexplored only shows 488 koroks as found.

Thanks a lot.

**Comment by lud99** [comment]
Hi and thank you :) 
Tears of the Kingdom has 900 koroks (800 normal, 100 lonely) but 1000 korok seeds. The app shows the number of koroks found and not the actual korok seeds. Could this be the issue?

**Comment by alcabcucu** [comment]
I guess it is, thanks. In the loading screen I can see that I have 562 korok seeds. So I'm sure thats the reason. I didn't consider that in some cases I was receiving two korok seeds when carrying a korok in order to meet "his friend".

Thanks a lot, and sorry for the inconvinience.
